language: cpp

notifications:
  email: false

sudo: required

install:
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.sh
  - sudo sh cmake-3.2.3-Linux-x86_64.sh --skip-license --prefix=/usr
  - sudo apt-get install libtommath0 libtommath-dev
  - sudo python -m pip install Mako fdb
  - svn co http://svn.code.sf.net/p/firebird/code/qa/fbtest/trunk/ fbtest
  - svn co http://svn.code.sf.net/p/firebird/code/qa/fbt-repository/trunk/ fbtest/fbt

script:
  - ./autogen.sh
  - make
  - sudo echo `pwd`/gen/Release/firebird/lib | sudo tee --append /etc/ld.so.conf
  - sudo ldconfig
  - sudo ./gen/Release/firebird/bin/gsec -add sysdba -pw masterkey
  - chmod 777 travis.sh
  - sudo ./travis.sh start_server &
  - ./travis.sh dummy_output &
  - ./travis.sh skip_tests
  - sleep 3
  - cd fbtest/fbt
  - python ../fbtest.py -d `pwd`/tmp -b `pwd`/../../gen/Release/firebird/bin -v -x -k ../../skip.txt
